name: Generate Trivy SBOM

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - src/**
      - .github/workflows/trivy-sbom.yml

permissions:
  contents: write

jobs:
  trivy-sbom:
    name: Generate SBOM with Trivyy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build container image
        run: docker build --tag sbom-submission-example:${{ github.sha }} .

      - name: Generate Trivy SBOM
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: sbom-submission-example:${{ github.sha }}
          format: spdx-json
          output: trivy-sbom.spdx.json
          scanners: vuln

      - name: Submit Trivy SBOM to Dependency Graph
        uses: ./.github/actions/sbom-dependency-submission
        with:
          correlator: trivy-sbom
          sbom-path: trivy-sbom.spdx.json
          token: ${{ secrets.GITHUB_TOKEN }}